### ISSUE TITLE
Failed to resolve: de.golfgl.gdxgameanalytics:gdx-gameanalytics-desktop:0.1.4

### ISSUE THREAD

**Issue by itsabhiaryan** [MrStahlfelge/gdx-gameanalytics#3]
After adding corresponding dependency in each platform/module, when I synced I got below error.

```
ERROR: Failed to resolve: de.golfgl.gdxgameanalytics:gdx-gameanalytics-desktop:0.1.4
Show in Project Structure dialog
Affected Modules: desktop
```

GDXVersion : 1.9.10
gaVersion : 0.1.4

Added below line in desktop dependency section
 
`        api "de.golfgl.gdxgameanalytics:gdx-gameanalytics-desktop:$gaVersion"
`

**Comment by MrStahlfelge** [comment]
It's included in 0.1.5-SNAPSHOT only, sorry. I'll make a new release soon.

**Comment by itsabhiaryan** [comment]
@MrStahlfelge Thanks for your quick response. 

I tried to use/include SNAPSHOT version but I think that is not published to any remote repo.

**Comment by MrStahlfelge** [comment]
You are probably right. I'll make a release within the next few hours!

**Comment by MrStahlfelge** [comment]
It is published, maybe you can already fetch it. If not, wait another 30 minutes.

**Comment by itsabhiaryan** [comment]
Perfect, Thanks.
